spring:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema.sql
        - classpath:sql/data.sql
  datasource:
    url: 'jdbc:h2:mem:cookie;MODE=Postgresql;'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
